# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/prana/Downloads/Processor/Processor.srcs/sources_1/ip/mem_rom_1/mem_rom.xci
# IP: The module: 'mem_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prana/Downloads/Processor/Processor.gen/sources_1/ip/mem_rom/mem_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/prana/Downloads/Processor/Processor.srcs/sources_1/ip/mem_rom_1/mem_rom.xci
# IP: The module: 'mem_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prana/Downloads/Processor/Processor.gen/sources_1/ip/mem_rom/mem_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
